version: '3.4'

services:
  video_blog_api:
    container_name: videoblog_api
    hostname: videoblog_api
    ports:
      - '7240:7240'
      - '5240:5240'
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: video_blog_api/Dockerfile
    networks:
      backend:
        ipv4_address: 172.16.1.3


  postgres:
    container_name: postgres_video_blog
    hostname: postgres_video_blog
    image: postgres:15.1
    ports:
      - '15432:5432'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/data/postgres"
    volumes:
      - './db:/data/postgres'
    networks:
      backend:
        ipv4_address: 172.16.1.4

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24